SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE NUEVO_ALUMNO(
    vDNI VARCHAR2,
    vAPENOM VARCHAR2,
    vDIREC VARCHAR2,
    vPOBLA VARCHAR2,
    vTELEF NUMBER
    )
    IS
BEGIN
    INSERT INTO ALUMNOS VALUES (vDNI,vAPENOM,vDIREC,vPobla,vTelef);
    DBMS_OUTPUT.PUT_LINE('Alumno insertado correctamente');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('DNI ya existe');
END;