SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE CAMBIAR_NOTA(
    DNI VARCHAR2,
    COD NUMBER,
    vFECHA NOTAS.fecha%TYPE;
    NOTA NUMBER
    )
    IS
vNOTA_ACTUAL NOTAS.nota%TYPE;
BEGIN
SELECT NOTA INTO vNOTA:ACTUAL
FROM NOTAS
WHERE vDNI=dni AND vCOD=cod AND vFECHA=fecha;

  UPDATE  NOTAS SET NOTA=NOTA AND FECHA=SYSDATE WHERE DNI=DNI AND COD=COD);
    EXCEPTION

      WHEN NO_DATA_FOUND THEN

        DBMS_OUTPUT.PUT_LINE('No hay datos');

      WHEN OTHERS THEN

       DBMS_OUTPUT.PUT_LINE('DNI O CÓDIGO INVÁLIDO');

END;