SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE NUEVA_NOTA(
    DNI VARCHAR2,
    COD NUMBER,
    NOTA NUMBER
    )
    IS
BEGIN
   INSERT INTO NOTAS VALUES (DNI,COD,SYSDATE,NOTA);
    EXCEPTION

      WHEN NO_DATA_FOUND THEN

        DBMS_OUTPUT.PUT_LINE('No hay datos');

      WHEN OTHERS THEN

       DBMS_OUTPUT.PUT_LINE('DNI O CÓDIGO INVÁLIDO');

END;