SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE CAMBIAR_NOTA2(
    NOMBRE ALUMNOS.APENOM%TYPE,
    nASIGNATURA ASIGNATURAS.NOMBRE%TYPE,
    nNOTA NOTAS.NOTA%TYPE
)
IS
    vNOMBREASIG VARCHAR;
    COD_NOTA NUMBER;
BEGIN
-- Recuperar codigo de alumno
SELECT DNI INTO COD FROM ALUMNOS WHERE APENOM=NOMBRE;
-- Recuperar codigo de la nota
SELECT COD INTO COD_NOTA FROM ASIGNATURAS WHERE NOMBRE=NOMBREASIG;
-- Actualizar las notas
UPDATE NOTAS
SET NOTA=nueva_nota
where cod=vcod and dni=vDNI AND FECHA=vfecha;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('La nota no existe');
END;